---
ruby_version: ruby-2.0.0-p353
common_essential_packages:
  - autoconf
  - automake
  - bison
  - build-essential
  - bash-completion
  - curl
  - dnsutils
  - git
  - htop
  - fail2ban
  - imagemagick
  - iotop
  - libc6-dev
  - libgdbm-dev
  - libffi-dev
  - libmagickwand-dev 
  - libncurses5-dev
  - libpq-dev
  - libreadline6
  - libreadline6-dev
  - libsqlite3-dev
  - libssl-dev
  - libtool
  - libyaml-dev
  - libxml2-dev
  - libxslt1-dev
  - make
  - openssl
  - pkg-config
  - python-pycurl
  - vim
